name: hp_mobile
description: A Flutter app for corporate login system
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/crop.png
    - assets/login_bg.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
